name: Shared API Build Action

on:
  workflow_call:
    inputs:
      isForDeploy:
        description: 'Is build stand-alone or part of deploy?'
        type: boolean
        required: true
      apiName:
        description: 'Name of api being built'
        type: string
        required: true
      branchName:
        description: 'Branch name which triggered action (github.ref_name)'
        type: string
        required: true
      nodeVersion: 
        description: 'Node version used for build'
        type: number
        required: false
        default: 18
    secrets:
      SLACK_WEBHOOK_DEV_NOTIFICATIONS:
        required: true      

jobs:
  build:
    name: Build ${{ inputs.apiName }}
    runs-on: ubuntu-22.04
    steps:
      # - name: First Interaction
      #   uses: actions/first-interaction@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     issue-message: 'This is your first submitted issue, THANK YOU! Someone will review shortly.'
      #     pr-message: 'This is your your first PR, THANK YOU! Someone will review shortly.'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ inputs.nodeVersion }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: npm ci, run validate
        run: |
          cp .env.sample .env
          npm ci
          npm run validate
          rm .env
        env:
          CI: true
          HUSKY: 0
      - name: Post-Build Copies
        run: |
          cp ./package.json __build__/
          cp ./package-lock.json __build__/
          cp ./Dockerfile __build__/
          git rev-list --count ${{ inputs.branchName }} > __build__/ccnt.txt
        if: inputs.isForDeploy
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: tc-api
          path: __build__
        if: inputs.isForDeploy
      - name: Slack Failure Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: CI onPush Action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'
