name: Redeploy gateway
# Redeploys GraphQL gateway forcing it to reload schema's all sub-graphs

on:
  workflow_call:
    inputs:
      runMemory:
        description: 'Amount of memory to allocate to google run'
        type: string
        required: false
        default: '256Mi'
      runTimeout:
        description: 'Timeout in seconds for google run'
        type: number
        required: false
        default: 90
    secrets:
      GCLOUD_AUTH:
        required: true
      GCP_PROJECT_ID:
        required: true
      SLACK_WEBHOOK_DEV_NOTIFICATIONS:
        required: true
      STELLATE_TOKEN:
        required: true
      STELLATE_SERVICE:
        required: true

jobs:
  redeploy:
    name: Redeploy
    runs-on: ubuntu-22.04
    steps:
      - name: Setup google auth for github actions
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}          
      - name: Setup gcloud CLI action
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '428.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Redeploy on Cloud Run
        # Environment vars should remain between deploys if not specified in command
        run: |
          gcloud run deploy gateway --image us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway --region=us-central1 --platform=managed --allow-unauthenticated --timeout=${{ inputs.runTimeout }} --memory=${{ inputs.runMemory }} --cpu=1
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      - name: Slack Failure Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'
  stellate:
    name: Push Stellate rules
    runs-on: ubuntu-22.04
    needs: [redeploy]
    steps:
      - name: Use node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Push to Stellate
        run: |
          npm version
          npx stellate version
          npx stellate pull --service ${{ secrets.STELLATE_SERVICE }}
          npx stellate push schema --service ${{ secrets.STELLATE_SERVICE }}
        env:
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}
          STELLATE_SERVICE: ${{ secrets.STELLATE_SERVICE }}
          CI: true
          HUSKY: 0
      - name: Slack Failure Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: Push Master CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: job.status == 'failure' || job.status == 'cancelled'

